In [ ]:
# Apriori

In [1]:
!pip install apyori

Requirement already satisfied: apyori in c:\users\tapaswini halder\anaconda3\lib\site-packages (1.1.2)

In [2]:
# Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
pip install datasets

Requirement already satisfied: datasets in c:\users\tapaswini halder\anaconda3\lib\site-packages (2.14.4)
Requirement already satisfied: numpy>=1.17 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (1.24.3)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (11.0.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (4.65.0)
Requirement already satisfied: xxhash in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (3.3.0)
Requirement already satisfied: multiprocess in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec[http]>=2021.11.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (2023.3.0)
Requirement already satisfied: aiohttp in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (3.8.3)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.14.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (0.16.4)
Requirement already satisfied: packaging in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (23.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from datasets) (6.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: filelock in c:\users\tapaswini halder\anaconda3\lib\site-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (3.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (4.7.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from requests>=2.19.0->datasets) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from requests>=2.19.0->datasets) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from requests>=2.19.0->datasets) (2023.7.22)
Requirement already satisfied: colorama in c:\users\tapaswini halder\anaconda3\lib\site-packages (from tqdm>=4.62.1->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from pandas->datasets) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\tapaswini halder\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import datasets

In [6]:
import pandas as pd

data_set = pd.read_excel("Netflixmovviereccomendation.xlsx", header=None)
transactions = []

for i in range(0, 7466):
    transactions.append([str(data_set.values[i, j]) for j in range(0, 20)])

In [7]:
print(data_set)

                            0                   1   \
0        The Lord of the rings     Cinema Paradiso
1     The Shawshank Redemption          Fight Club
2                The Godfather                 NaN
3       The Godfather: Part II               Se7en
4              The Dark Knight    The Intouchables
...                        ...                 ...
7461              Modern Times              psycho
7462  The Shawshank Redemption               Billa
7463             Prision Break                 NaN
7464            Harry Potter 2            Whiplash
7465              Pulp Fiction  Back to the Future

                                      2   \
0                                  Se7en
1                           Pulp Fiction
2                                    NaN
3                                    NaN
4        One Flew Over the Cuckoo's Nest
...                                  ...
7461                          Braveheart
7462                        Pulp Fiction
7463                                 NaN
7464                                 NaN
7465  Star Wars: Episode IV - A New Hope

                                                     3                 4   \
0                                Avengers: Infinity War       The Shining
1                                                   NaN               NaN
2                                                   NaN               NaN
3                                                   NaN               NaN
4     whole wheat Star Wars: Episode V - The Empire ...          Whiplash
...                                                 ...               ...
7461                                                NaN               NaN
7462      The Lord of the Rings: The Return of the King  Django Unchained
7463                                                NaN               NaN
7464                                                NaN               NaN
7465                                       12 Angry Men               NaN

                 5                           6          7            8   \
0     High and Low   Terminator 2: Judgment Day  Toy Story  City of God
1               NaN                         NaN        NaN          NaN
2               NaN                         NaN        NaN          NaN
3               NaN                         NaN        NaN          NaN
4               NaN                         NaN        NaN          NaN
...             ...                         ...        ...          ...
7461            NaN                         NaN        NaN          NaN
7462       Whiplash                         NaN        NaN          NaN
7463            NaN                         NaN        NaN          NaN
7464            NaN                         NaN        NaN          NaN
7465            NaN                         NaN        NaN          NaN

                               9             10        11             12  \
0     Witness for the Prosecution  12 Angry Men  Whiplash  Black Panther
1                             NaN           NaN       NaN            NaN
2                             NaN           NaN       NaN            NaN
3                             NaN           NaN       NaN            NaN
4                             NaN           NaN       NaN            NaN
...                           ...           ...       ...            ...
7461                          NaN           NaN       NaN            NaN
7462                          NaN           NaN       NaN            NaN
7463                          NaN           NaN       NaN            NaN
7464                          NaN           NaN       NaN            NaN
7465                          NaN           NaN       NaN            NaN

            13               14                            15  \
0     Hamilton  The Dark Knight  Once Upon a Time in the West
1          NaN              NaN                           NaN
2          NaN              NaN                           NaN
3          NaN              NaN                           NaN
4          NaN              NaN                           NaN
...        ...              ...                           ...
7461       NaN              NaN                           NaN
7462       NaN              NaN                           NaN
7463       NaN              NaN                           NaN
7464       NaN              NaN                           NaN
7465       NaN              NaN                           NaN

                      16                  17      18                        19
0     The Great Dictator  Back to the Future  Aliens  Comedy nights with Kapil
1                    NaN                 NaN     NaN                       NaN
2                    NaN                 NaN     NaN                       NaN
3                    NaN                 NaN     NaN                       NaN
4                    NaN                 NaN     NaN                       NaN
...                  ...                 ...     ...                       ...
7461                 NaN                 NaN     NaN                       NaN
7462                 NaN                 NaN     NaN                       NaN
7463                 NaN                 NaN     NaN                       NaN
7464                 NaN                 NaN     NaN                       NaN
7465                 NaN                 NaN     NaN                       NaN

[7466 rows x 20 columns]

In [8]:
# Eclat Training on dataset

In [9]:
from apyori import apriori
rules=apriori(transactions=transactions, min_support=0.003, min_confidence=0.2, min_lift= 3,min_length = 2, max_length = 2)

In [10]:
results=list(rules)

In [11]:
results

[RelationRecord(items=frozenset({'Captain America', 'Black Panther'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Captain America'}), items_add=frozenset({'Black Panther'}), confidence=0.24509803921568626, lift=5.140174047146949)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'Game of thrones'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20512820512820512, lift=3.1001764766946955)]),
 RelationRecord(items=frozenset({'Kanan Gill Comedy', 'Comedy nights with Kapil'}), support=0.008036431824270024, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2714932126696833, lift=4.103174748566509)]),
 RelationRecord(items=frozenset({'Prision Break', 'Game of thrones'}), support=0.004553978033753014, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Prision Break'}), confidence=0.2905982905982906, lift=4.832086498010774)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'Harry Potter 1'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.36752136752136755, lift=4.642833383950135)]),
 RelationRecord(items=frozenset({'Harry Potter 1', 'The Lord of the rings'}), support=0.005089740155371015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.3247863247863248, lift=4.523982650848323)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'crimes of grindelwald'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'crimes of grindelwald'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.3006993006993007, lift=3.7986818595955647)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception'}), support=0.015938923118135547, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar'}), items_add=frozenset({'inception'}), confidence=0.3216216216216216, lift=3.262536721504113)]),
 RelationRecord(items=frozenset({'The Wolf of Wall Street', 'inception'}), support=0.005357621216180016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Wolf of Wall Street'}), items_add=frozenset({'inception'}), confidence=0.3773584905660377, lift=3.8279327317473335)])]

In [12]:
def inspect(results):
    product1         = [tuple(result[2][0][0])[0] for result in results]
    product2         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(product1, product2, supports, confidences, lifts))
DataFrame_intelligence = pd.DataFrame(inspect(results), columns = ['product1', 'product1', 'Support', 'Confidence', 'Lift'])

In [13]:
DataFrame_intelligence

,product1,product1,Support,Confidence,Lift
0,Captain America,Black Panther,0.003349,0.245098,5.140174
1,Game of thrones,Comedy nights with Kapil,0.003215,0.205128,3.100176
2,Kanan Gill Comedy,Comedy nights with Kapil,0.008036,0.271493,4.103175
3,Game of thrones,Prision Break,0.004554,0.290598,4.832086
4,Harry Potter 1,Harry Potter 2,0.005759,0.367521,4.642833
5,Harry Potter 1,The Lord of the rings,0.005090,0.324786,4.523983
6,crimes of grindelwald,Harry Potter 2,0.005759,0.300699,3.798682
7,Interstellar,inception,0.015939,0.321622,3.262537
8,The Wolf of Wall Street,inception,0.005358,0.377358,3.827933

In [14]:
DataFrame_intelligence.nlargest(n = 10, columns = 'Lift')

,product1,product1,Support,Confidence,Lift
0,Captain America,Black Panther,0.003349,0.245098,5.140174
3,Game of thrones,Prision Break,0.004554,0.290598,4.832086
4,Harry Potter 1,Harry Potter 2,0.005759,0.367521,4.642833
5,Harry Potter 1,The Lord of the rings,0.005090,0.324786,4.523983
2,Kanan Gill Comedy,Comedy nights with Kapil,0.008036,0.271493,4.103175
8,The Wolf of Wall Street,inception,0.005358,0.377358,3.827933
6,crimes of grindelwald,Harry Potter 2,0.005759,0.300699,3.798682
7,Interstellar,inception,0.015939,0.321622,3.262537
1,Game of thrones,Comedy nights with Kapil,0.003215,0.205128,3.100176